CC = gcc
CFLAGS = -Wall -Wextra -Iinclude -Ilibs/libsodium/include -I./src -std=c11
LDFLAGS = -Llibs/libsodium/lib -lsodium -lws2_32

SRC = $(wildcard src/*.c)
OBJ = $(SRC:src/%.c=build/%.o)
DEPS = $(OBJ:.o=.d)
OUT = build/bvault.exe

# Default target
all: $(OUT)

# Link all object files into the final executable
$(OUT): $(OBJ)
	@if not exist build mkdir build
	$(CC) $(OBJ) $(LDFLAGS) -o $(OUT)

# Compile each .c -> .o with automatic dependency generation
build/%.o: src/%.c | build
	$(CC) $(CFLAGS) -MMD -MP -c $< -o $@

# Make sure the build directory exists
build:
	@if not exist build mkdir build

# Include dependency files (auto-generated by -MMD)
-include $(DEPS)

# Run target
run:
	$(OUT)

# Clean target
clean:
	@if exist build rmdir /s /q build

.PHONY: all clean run
